### ISSUE TITLE
Structure packing

### ISSUE THREAD

**Issue by sagamusix** [free-audio/clap#21]
Structure packing isn't necessarily standardized between all compilers targetting the same platform. The VST SDK enforces the same alignment for all supported compilers on each system. CLAP doesn't do this yet, so structs like `clap_event_note` end up with a packing that might end up differently on different compilers (as the natural placement of a `double` value cannot be at byte 12, which would be the next free space after 3 32-bit integers). In practice this means the `double` will be placed at offset 16 instead.

I'd suggest to have a well-defined structure packing for all structs in CLAP (doesn't even have to be different from what is currently being done, it just needs to be defined at all), and/or avoid structs with non-natural alignment to begin with (in this particular example `double` could be replaced by `float` if the reduced precision is agreeable, but for other structs that may not always be possible, especially as soon as pointers are involved).

**Comment by abique** [comment]
I'm not so sure which direction to take.
I'll think about it, thank you very much!

**Comment by abique** [comment]
I've found two possible approaches:
1. use `#pragma pack(push, 1)` and `#pragma pack(pop)` in every files
2. use `_Alignas`, https://en.cppreference.com/w/c/language/_Alignas

**Comment by sagamusix** [comment]
I think `alignas` might not completely solve the problem, as it just ensures the alignment of individual members is at least the given amount but it doesn't standardize the structure packing. See the warning here: https://docs.microsoft.com/en-us/cpp/preprocessor/pack?view=msvc-170 "In Visual Studio 2015 and later you can use the standard `alignas` and `alignof` operators, which unlike `__alignof` and `__declspec( align )` are portable across compilers. The C++ standard doesn't address packing, so you must still use `pack` (or the corresponding extension on other compilers) to specify alignments smaller than the target architecture's word size."

So I'm afraid that to the best of my knowledge, `#pragma pack` is currently the only way to really solve this issue.

**Comment by abique** [comment]
Thank you very much for your input!
I also think that a `#pragma pack(push, 1)` is the easy way to go.

**Comment by abique** [comment]
Do I also need to force the calling convention everywhere?

**Comment by sagamusix** [comment]
`#pragma pack(push, 1)` is not a good idea - it breaks the natural alignment and can thus decrease performance (especially on platforms where unaligned loads are forbidden). VST2 uses `#pragma pack(push, 8)` which I think is the default on Windows anyway. VST3 appears to be using a packing of 4 bytes instead: https://github.com/steinbergmedia/vst3_pluginterfaces/blob/2ad397ade5b51007860bedb3b01b8afd2c5f6fba/vst/vstpshpack4.h

As you can see there, Steinberg also supports the Borland C++ compiler there which uses a different syntax, but `#pragma pack` is more widespread and used by virtually all other compilers.

Forcing a calling convention is definitely required on Windows at least. `__cdecl` would be the usual option for that, I think. I think on other platforms this might not be necessary.

**Comment by abique** [comment]
https://github.com/steinbergmedia/vst3_pluginterfaces/blob/master/base/falignpush.h
They align by 16, I'm not sure why unless they want to load vectors from the structs.

**Comment by abique** [comment]
So here is what I'm thinking to do:
- use pragma pack(8) on 64 bits
- use pragma pack(4) on 32 bits
- use alignas for fine tuning

**Comment by abique** [comment]
I've done some work in https://github.com/free-audio/clap/blob/next/include/clap/events.h

**Comment by spongeboburu** [comment]
Hi there! Thanks for starting clap.

I work almost exlusively with writing portable C99 audio software that must work with many esoteric architectures and compilers, I might have some useful input. My recommendation would be that you only use the features defined in the standard and avoid all compiler specific features. It is sometimes more cumbersome, but if your goal is portability it is the safest way to avoid future headaches.

For instance #pragma once is pretty easily replaced by the regular #ifndef header guard.
I'm also not sure why we need to force alignment of the struct, the restrictions are imposed by the architecture. Just guessing, Steinberg might have gone with 16 since it is the largest alignment on 64-bit intel and arm (long double for example).
I also just wanted to mention that stdalign.h is C11 and while C11 is much better than C99 it may be partially or wholly missing (yes, still in 2020!) in some compilers, one example is msvc.

And final question, do you have any communication set up for this project? I would not mind joining a slack or discord channel dedicated to the development of clap.

Have a nice day!

**Comment by ihameed** [comment]
@abique:

I don't think you really have to do much, if anything, at all. On Windows: MinGW clang, MinGW gcc, clang-cl, and msvc use the same layout for structs by default. On Linux: gcc and clang use compatible data layouts by default. If you do feel like you have to do something, you should:

- assume that `int16_t`, `int32_t`, `int64_t`, `float`, and pointers of any type are aligned in the obvious way;
- use `#pragma pack(push, 8)`;
- insert explicit padding by using appropriately-sized char arrays; and
- use a `_Static_assert` workalike to verify that your datatypes have the size and alignment you expect.

It is possible to make clang, gcc, and msvc use different rules for struct layouts ([`-fpack-struct`](https://gcc.gnu.org/onlinedocs/gcc/Code-Gen-Options.html), [`/Zp`](https://docs.microsoft.com/en-us/cpp/build/reference/zp-struct-member-alignment)). The suggestion above will make your header mean the same thing even if the programmer uses these flags.

On 32-bit x86 Windows, `double` is aligned to 8 bytes. On 32-bit x86 (but not armv7) Linux, `double` is aligned to 4 bytes. Explicit padding and explicit alignas can sort of "fix" this, but it's not actually a problem for CLAP; CLAP is an ABI for shared library plugins and not a protocol for cross-OS communication. All that matters is that the compilers used to create hosts and plugins agree on some arbitrary convention for use within the platform.

Rust and Zig both have built-in support for C-style struct layout. They do exactly what you'd expect. Adding lots of per-field alignas specifiers will increase the amount of work people will have to do to use CLAP from these languages.


> https://github.com/steinbergmedia/vst3_pluginterfaces/blob/master/base/falignpush.h They align by 16, I'm not sure why unless they want to load vectors from the structs.

That's not setting a default minimum or exact alignment. This doesn't mean "subsequent datatype definitions will have at least/exactly 16 byte alignment"; instead this means "any datatype definition that follows, unless specified otherwise with alignas, will have at most 16 byte alignment". This doesn't actually change anything for any mainstream compiler on any mainstream platform using default compiler settings. You can see this for yourself: https://godbolt.org/z/nEoPsod19


@sagamusix:

> Forcing a calling convention is definitely required on Windows at least. `__cdecl` would be the usual option for that, I think. I think on other platforms this might not be necessary.

You don't need to do this on Windows. MinGW clang, MinGW gcc, clang-cl, and msvc will all use the same calling convention by default (and they all call it "cdecl") on 32-bit and 64-bit Windows. These compilers support flags, like [`-mrtd`](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html) and [`/Gr`](https://docs.microsoft.com/en-us/cpp/build/reference/gd-gr-gv-gz-calling-convention), that will change the defaults. There might be some value in explicitly specifying a calling convention, so that users who do use `-mrtd` or `/Gr` can still use the CLAP headers verbatim, but I don't think this is a big deal.

You don't need to do this on other mainstream platforms. I have no idea about consoles or esoteric platforms though.


Implicitly assumed:
- mainstream platforms: Windows/Linux/FreeBSD/macOS on amd64/i386/aarch64/armv7 etc. 8 bit bytes, byte addressed memory, virtual memory, etc. No weird stuff.
- mainstream compilers: clang, gcc, msvc. On Windows: MinGW or MSVC ABI.

**Comment by sagamusix** [comment]
Wasn't there at least one popular compiler using a different calling convention on Windows? Maybe that has changed since the last time I looked into this issue (which was admittedly a long time ago).

**Comment by signaldust** [comment]
Even though __cdecl is usually the default (whatever it happens to mean on any given platform), I'd personally vote for specifying it explicitly (or using something like CLAPCALL that expands to __cdecl) for anything and everything on the ABI boundary just to make the headers robust against compiler settings (eg. to allow compilation with a compiler specific "fast call" as the default).

In general, I'd vote for keeping an API like this as agnostic to compiler settings and build systems as humanly possible.

**Comment by abique** [comment]
So gcc expects the function attribute at the end and msvc at first.

It'd look like `void (CLAP_CALL_MSVC *fct)(void) CLAP_CALL_GCC;`? That would be ugly.

**Comment by sagamusix** [comment]
You should be able to place `__attribute((__cdecl__))` in the same position as for MSVC. However, it seem to emit an annoying warning that the attribute is ignored (presumably because it's the default). Putting a different calling convention there (e.g. `__attribute__((ms_abi))`) confirms that its works and doesn't emit a warning.

I'd still undo the changes that use `alignas` in events.h. As pointed out by @ihameed above, `#pragma pack` is the solution that should do the trick and litters the header less.

**Comment by signaldust** [comment]
I think the GCC attribute is just "cdecl" without any underscores, so that might be what's triggering the warning.

**Comment by signaldust** [comment]
So I looked at this in Godbolt and __cdecl__ gets converted to cdecl by GCC before it emits the warning (at least with -Wall). However, at least for x86 this warning only happens with 64-builds, where the attribute arguably is not useful (since there is basically just one calling convention), where as with -m32 it works as expected (and actually generates marginally different preample compared to say "fastcall" in my little test function, so I guess it actually does something too).

So it might make sense to have a placeholder macro and then just let it expand to empty on platform where it's not actually needed. That way it'd be easy for a user to patch in something in bulk if necessary. Might not exactly be high priority though.

**Comment by p0nce** [comment]
Hello I see there are lots of `#pragma pack` in CLAP.
As someone who ported VST2/VST3/AAX/AU headers to another native language (D): it is really harder than expected to reason and translate `#pragma pack`, unless it's for very small struct that have to be `pragma pack(1)` it makes things a lot more difficult. The default packing already does things rather efficiently.
Also there is no way to translate that into some other language (without making the layout explicit), because the alignement directive may be different. `align` in D means "at a minimum" vs packing in C++ means "at most".

VST3 does it best with a (platform-specific) macro to check size of struct at compile-time, on different arch.

**Comment by abique** [comment]
I to have each fields exactly aligned by their `sizeof()`.
I think it would cover everything.

**Comment by abique** [comment]
This is interesting, I think I've seen Walter Bright suggesting that VST3 should use `alignas`.
https://github.com/steinbergmedia/vst3_pluginterfaces/issues/9
Isn't he the authors of D himself? ;-)

**Comment by sagamusix** [comment]
> it is really harder than expected to reason and translate #pragma pack

the original intent of this issue was essentially to codify the native defaults that are to be expected by the platform anyway (as signaldust says above, mostly so that a project using different defaults can still safely include those headers). If it makes it harder to port it to a different language, something went wrong and needs to be revised.

**Comment by abique** [comment]
Isn't it doing it?
https://dlang.org/spec/attribute.html#align

**Comment by p0nce** [comment]
@abique yes there is a small story there, Bright tried to say he wouldn't have to implement `pragma(pack)` for ImportC (a D compiler feature that will let us import C directly, but currently it is far from working). we told him it was used everywhere in native land, and that it had incompatible semantics than D's `align`. He finally implemented `pragma(pack) for `ImportC`. At this point he didn't understood that `_Alignas` and `pragma(pack)` were not the same feature. Still we have no `pragma(pack)` in D as of now.

Semantics of D's `align(8)` is "this will be aligned to _at least_ multiple-of-8" (it can only add padding)
Semantics of C's `pragma(pack, 8)` is "this will be aligned to _at most_ multiple-of-8" (it can only remove padding)
Hence it's really not that trivial to translate any significant amount of pragma(pack). `align:` **cannot** do it.

C and D have the same alignment defaults when you don't specify anything though. Most portable C libraries just specify nothing.
To put some weights on my claim: here is what happens with pragma pack: 

CLAP currently puts `pragma(pack)`on every struct by default, and not only 1, so (form my point of view) it is doing worse than other plugin formats with that regards. This will also help other language I believe, like Pascal/Rust etc.

At the very least a macro like `SMTG_TYPE_SIZE_CHECK` in the VST3 SDK would help immensely.

**Comment by abique** [comment]
What about:
 - do absolutely nothing (no pragmas, no alignas)
 - make it required to use a compiler that is compatible to what msvc/gcc/clang would do with **no compiler flags**

It seems that today any serious compiler will try to be compatible with those major one, and anyone going for a compiler with a non-standard ABI is shooting himself in the foot.

**Comment by signaldust** [comment]
Ideally one would probably make sure that everything packs naturally tight, but if it's too late for that, then I'd be inclined to support the idea of just leaving it as "do nothing, rely on platform defaults" 'cos I'd imagine just about every FFI of just about every language is capable of emitting platform default c-structs and for most platform this is "natural alignment" anyway... and as has been noted, on some architectures you really don't want to specify wrong alignment even by accident.

**Comment by robbert-vdh** [comment]
Are C-structs without explicit representation specifiers always ABI compatible between mingw and MSVC like they are with GCC and Clang on other platforms?

**Comment by signaldust** [comment]
Both GCC and Clang can pack either "MSVC style" or "GCC style" (where I'd guess the latter matches x86 Linux), see for example: https://lists.fedoraproject.org/pipermail/mingw/2008-November/000083.html

This thread: https://github.com/appveyor/ci/issues/3545 suggests that as of GCC 4.7 and LLVM 11, ms_struct should be the default on Win32 for both compilers, but the option (command line, pragma or attribute) is fairly old.

**Comment by p0nce** [comment]
> do absolutely nothing (no pragmas, no alignas)

This create the least work for me, that's for sure.
If something has to be tight in memory, `pragma pack(1)` is much easier to emulate than 2, 4, or 8. `pragma pack(1)` is much easier as you can count the byte as it's the same size in all ABIs!

**Comment by abique** [comment]
Is anyone aware of a tool that can track binary compatibility?
I imagine it could create a dump of every structs, with:
- sizeof struct
- offsetof for each attributes

Then we'd get a json, that we can compare from version to version, and clap would provide a test that you can compile and run to verify if your compiler produces the expected layout.

**Comment by abique** [comment]
https://github.com/lvc/abi-tracker
https://abi-laboratory.pro/index.php?view=tracker

**Comment by abique** [comment]
I went with the following solution:
- protect everything with a pragma pack 16
- remove alignas

That's what vst3 is doing.
The only purpose of the pragma pack is to protect a developer doing:
```C
#pragma pack(push, 1)
// ...
// forgot to pop the pragma
#include <clap/clap.h>
```
So I could consider removing the pragma as well.

**Comment by abique** [comment]
> > So I could consider removing the pragma as well.
> 
> That's probably the best option after all this discussion.

Yes

**Comment by abique** [comment]
> Is that a breaking change or not, out of curiosity?

I think not, because even with packing and alignas we had a natural alignment.
Also until version 1 we require the clap version to be exactly the same.
