### ISSUE TITLE
Logarithmic parameters?

### ISSUE THREAD

**Issue by sadko4u** [free-audio/clap#285]
Hello!

Just noticed that CLAP doesn't provide logarithmic parameters (for, example, the Frequency).
I mean, the host does not know anything about the parameter scale like in [PortProperties:logarithmic](https://lv2plug.in/ns/ext/port-props#logarithmic).

Would be a good idea to add such flag.

**Comment by abique** [comment]
Hi,

It doesn't work like that with CLAP.
You should change the domain of your knob so it is linear, like using the pitch domain for frequencies instead.

**Comment by robbert-vdh** [comment]
These flags are inherently too limited because they cannot possibly represent all the different ways you'd want your parameter range to be scaled/skewed/transformed, which is probably part of the reason why CLAP didn't even bother with them. Either indeed make your parameter's domain linear, like using MIDI note IDs instead of frequencies, or just use `[0, 1]` and do the scaling in your plugin.

**Comment by abique** [comment]
Also modulation would not work well if the domain wasn't linear and the need to be applied before the domain conversion.
