### ISSUE TITLE
Standardized user-local Linux plugin search path

### ISSUE THREAD

**Issue by robbert-vdh** [free-audio/clap#46]
(moving from the conversion on https://github.com/free-audio/clap/commit/b902efa94e7a069dc1576617ebd74d2310746bd4)

For user-local plugins, the two options currently considered as mentioned in https://github.com/free-audio/clap/commit/b902efa94e7a069dc1576617ebd74d2310746bd4 are `~/.clap` and `~/.local/lib/clap`.

The arguments for `~/.clap` are that it's in line with what users would expect (as `~/.vst`, `~/.vst3` and `~/.lv2` will likely also exist on their system), while the argument against it is that it clutters up the home directory. My personal argument against `~/.local/lib/clap` is that it's not a standardized directory, and there's no associated environment variable defined in  the [XDG Base Directory](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) specification for controlling its location. And a third option is `$XDG_DATA_HOME`/`~/.local/share` which is meant for program data that can be shared across systems, but that may of course also not be a very discoverable location for users that try to install CLAP plugins from downloaded archives.

**Comment by baconpaul** [comment]
I had figured ~/.clap was by far the best; that's where I had the juce adapter install when it is in copy-on-build mode. Totally symmetric with the others, even though it is a little cluttering.

**Comment by SolarLiner** [comment]
I really do not like how polluted my home directory is, especially when standard directory exist for this very reason (that, and being able to efficiently tell my backups to save `.config` but *not* `.cache`).

Furthermore, this would break hosts under sandboxing, where the home directory isn't accessible by default, and giving hosts access to all of it *because* of this design decision makes little sense to me. Instead, standard directories like `$XDG_DATA_DIRS` will always be accessible, although set to namespaces locations, without having to punch big holes into the sandbox.

I really suggest the use of `$XDG_DATA_DIRS/clap` as a default, with potentially a fallback for `~/.clap`, though I don't think it would be hard for users of host applications to adapt to the change.

**Comment by abique** [comment]
`$XDG_DATA_DIRS` is a set of directories, so `$XDG_DATA_DIRS/clap` does not mean much, does it?
 
I've contacted the authors of the xdg spec to clarify what we should do, and maybe update the spec.

**Comment by robbert-vdh** [comment]
@SolarLiner I think this is very different. Individual applications shouldn't pollute the home directory, but `~/.clap` wouldn't belong to a single application. It would just be a standardized location to store CLAP plugin binaries. Just like `~/.config` (or `$XDG_CONFIG_HOME`) is a standardized location for applications to store configuration files, and `~/.cache` (or `$XDG_CACHE_HOME`) is a standardized location for applications to store temporary files that can be removed without any negative repercussions.

And there's no reason why this would break sandboxing. If you can pass through `~/.local/foo` to the sandbox, then you can also pass through `~/.clap`. Furthermore, VST2, VST3, and LV2 plugins will also continue to exist for a long time, and people's home directories also contain their DAW's configuration, project files, and sometimes sample libraries. So if people are running hosts under some sort of sandbox, then they'll likely end up passing through their entire home directory anyways.

**Comment by abique** [comment]
> @SolarLiner I think this is very different. Individual applications shouldn't pollute the home directory, but `~/.clap` wouldn't belong to a single application. It would just be a standardized location to store CLAP plugin binaries. Just like `~/.config` (or `$XDG_CONFIG_HOME`) is a standardized location for applications to store configuration files, and `~/.cache` (or `$XDG_CACHE_HOME`) is a standardized location for applications to store temporary files that can be removed without any negative repercussions.
> 
> And there's no reason why this would break sandboxing. If you can pass through `~/.local/foo` to the sandbox, then you can also pass through `~/.clap`. Furthermore, VST2, VST3, and LV2 plugins will also continue to exist for a long time, and people's home directories also contain their DAW's configuration, project files, and sometimes sample libraries. So if people are running hosts under some sort of sandbox, then they'll likely end up passing through their entire home directory anyways.

I agree. Still I'm curious to read what the xdg people have to say.

**Comment by SolarLiner** [comment]
I don't agree that "everybody does it wrong" is a good argument. Besides, `XDG_FATA_DIRS` can be used for shared data across applications; in fact there's nothing preventing VST liraries from being put there anyway. Most DAWs are configurable in their search is directories anyway.

Actually, I'd rather be in favor of directories being configurable anyways, a la VST2. It makes even more sense to me.

**Comment by abique** [comment]
It is a good thing to be able to configure your DAW search path, but it is a bad thing when the plugin installer asks you where to put files because it leads to inconsistent installation and unnecessary steps.

**Comment by lhanson** [comment]
There is no compelling reason whatsoever to clutter a user's home directory with yet another top-level vanity folder, and countless reasons against it.

> $XDG_DATA_DIRS is a set of directories, so $XDG_DATA_DIRS/clap does not mean much, does it?

Sure it does, it means "the user has explicitly given me a preference-ordered list of directories to look for data in". If you're looking for clap plugins, you look for the presence of a `clap` directory in that list. If you're writing data, you choose the first directory and put `clap/` there.

If some madman thinks that adding a specific backup rule for every single application they install is a great use of their time, they can `export XDG_DATA_DIRS="$HOME"`, but I really doubt anybody is going to go out of their way to do that if the default respects their preferences to begin with.

**Comment by SolarLiner** [comment]
Those reasons are not *actually* compelling. It doesn't make sense to do this in an unstandardized way just because it's the historic way. However there are very good reasons to use standardization whenever available, least of which is respecting conventions set by the system and/or user.

How, for example, do we tell applications to write somewhere else from `$HOME` if it is unwritable for some reason? There is a way to tell *every application* with a single configuration change instead of having to manually support each and every application under the sun. It's especially for this reason, along with an effort to unclutter the HOME directory, that the specifications were created in the first place.

"But VSTs are found in `~/.vst` !" - VST 2 is 21 years old, had only Windows in mind, and most probably predates the freedesktop standardization efforts. VST3 didn't follow then, and that's a shame, leading to more clutter, more specialized configuration, etc. This is an opportunity to take this standardization into account.

**Comment by abique** [comment]
`$XDG_DATA_DIRS` is a plural. To me it implies:
- it can contain 0 or many directories, hopefully just one
- if it contains many directories then which one to use? Also what happens if they are re-ordered?
- if there can be many directories maybe it means that it is a common operation to add or remove directories to it?
  - what happens when the user performs such an operation?
  - how is the plugin supposed to be aware and possibly update its installation when it happens?
- the plugin needs one stable location, not subject to random changes

Now back to reality, I'm using openbox on Archlinux and let's see what it actualy is:
```bash
echo $XDG_DATA_DIRS 
/home/abique/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
```
The only user-writable directory here is: `/home/abique/.local/share/flatpak/exports/share` which definitely does not sound like the place to install CLAP plugins.

On top of everything said, relying upon environment variables is fragile, they are initialized in various way depending on your login manager, window manager and even changed by your shell.

Maybe XDG provides the solution to our problem, but it is not `$XDG_DATA_DIRS`.

There are many things that are not perfect and we keep using them for 20 years. When something works well enough, that's what happen. So `~/.vst` is maybe not perfect, but it worked well enough so far.

**Comment by robbert-vdh** [comment]
> Those reasons are not _actually_ compelling. It doesn't make sense to do this in an unstandardized way just because it's the historic way. However there are very good reasons to use standardization whenever available, least of which is respecting conventions set by the system and/or user.

The point is to come up with a standardized place to store CLAP plugins. If the plugin standard says that `~/.clap` is the default installation location for user-local CLAP plugins, then it's a standardized way of storing them. And while I do personally hate it when applications place random (dot)files in my home directory, most users don't actually care or notice. For them it's just an easier and more familiar place to find their plugins. If you do want to have nothing in your home directory other than `.config`, `.local` and `.cache`, then you can of course always configure those things yourself. These standard plugin locations mostly serve as defaults for installers and DAWs. And again, `~/.clap` would be a standardized location, so that's very different from a random application placing dotfiles in your home directory.

> How, for example, do we tell applications to write somewhere else from `$HOME` if it is unwritable for some reason? There is a way to tell _every application_ with a single configuration change instead of having to manually support each and every application under the sun. It's especially for this reason, along with an effort to unclutter the HOME directory, that the specifications were created in the first place.

If that's the main goal, how about introducing a standardized `CLAP_PATH`? Quite a few DAWs already respect `VST_PATH`, VST3_PATH` and `LV2_PATH`. In fact, that's the only way to configure plugin search locations in Renoise.

> "But VSTs are found in `~/.vst` !" - VST 2 is 21 years old, had only Windows in mind, and most probably predates the freedesktop standardization efforts. VST3 didn't follow then, and that's a shame, leading to more clutter, more specialized configuration, etc. This is an opportunity to take this standardization into account.

It's not just `~/.vst`. `~/.lv2` is used frequently by convention, and `~/.vst3` is a standardized VST3 plugin directory as per the VST3 specification itself.

**Comment by lhanson** [comment]
I'm not invested in using `XDG_DATA_DIRS` specifically, it depends on the use case and I think that applies more to a situation where you're looking for existing data and more flexibility is required. `XDG_DATA_HOME` might be more relevant to this discussion.

> if it contains many directories then which one to use? Also what happens if they are re-ordered?

It's explicitly ordered by user preference, you don't need to guess. If they're re-ordered, you're still going to look for the first existing `clap` subdirectory if one is present in the list. If you're writing data and there's no existing directory, you believe the user when they tell you to use the first one in the list.

> if there can be many directories maybe it means that it is a common operation to add or remove directories to it?
>    what happens when the user performs such an operation?
>   how is the plugin supposed to be aware and possibly update its installation when it happens?

None of that matters if you follow the simple heuristic I just described.

I won't belabor the point because, again, I'm not arguing that `XDG_DATA_DIRS` is necessarily what's needed here. But I suspect similar objections would be raised to using `$XDG_DATA_HOME/clap`, and those objections just don't seem compelling at all.

**Comment by abique** [comment]
`$XDG_DATA_HOME` isn't defined on my system.

**Comment by lhanson** [comment]
> The point is to come up with a standardized place to store CLAP plugins. If the plugin standard says that ~/.clap is the default installation location for user-local CLAP plugins, then it's a standardized way of storing them.

Why does every bit of software need to reinvent the wheel for what is already a solved problem? This is precisely why the XDG standard exists in the first place.

> If that's the main goal, then how about introducing a standardized CLAP_PATH environment variable in the specification? Quite a few DAWs already respect VST_PATH, VST3_PATH and LV2_PATH. 

Great, now I have n+1 "standard" directories and environment variables to wrangle.

None of these arguments are novel to CLAP and have already been hashed out ad nauseam in countless other projects with much longer historical baggage and existing data.

Proposal: store plugin data in `$XDG_DATA_HOME/clap`. If `$XDG_DATA_HOME` is not set, default to `$HOME/.local/share` as per the spec.

**Comment by robbert-vdh** [comment]
CLAP is not a bit of software. It's a plugin standard. There's a big difference between picking a data for storage directory for an application (`${XDG_DATA_HOME:-$HOME/.local/share}/appname` is definitely the right choice there) and standardizing on a storage directory for an entire class of data files. My initial preference also went out for using `$XDG_DATA_HOME`, but thinking about it more I'm convinced that defaulting to `~/.clap` is going to be a much more familiar location for less technically inclined users. And you can still opt to not use that if you for whatever reason really want to do that.

**Comment by abique** [comment]
According to https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard
> `/usr/share` Architecture-independent (shared) data.

**Comment by abique** [comment]
This is the full spec: https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html
`libexec` could be a better place than `lib` but `lib` would work nevertheless.

**Comment by baconpaul** [comment]
> Proposal: store plugin data in `$XDG_DATA_HOME/clap`. If `$XDG_DATA_HOME` is not set, default to `$HOME/.local/share` as per the spec. Literally everybody wins.

I think you are conflating plugin data (which definitely can go to $XDG_DATA_HOME/plugin-name) with the plugin dll itself, which doesn't seem like it belongs in share. Several popular plugins install into `/usr/lib/vst3/foo` and put their data in `/usr/share/foo` (using the various XDG paths and CMAKE Install prefixes and so on); but the discussion here is about the former.

Hope that helps!
