### ISSUE TITLE
MPE in clap not working

### ISSUE THREAD

**Issue by TjShredder** [free-audio/clap#82]
Just loaded the clap version into Bitwig 4.2.4 and MPE does not work. The VST3 is fine though...

**Comment by baconpaul** [comment]
this is a report about surge right?

i think it is because of note expressions and the default clap using those rather than just transparent midi. Oddly, if you make the bitwig device non-MPE and surge MPE I bet it will work.

but i'm working now on note expressions on clap 0.25.

I'm gonna suggest we close this as being filed in the wrong place though (this is for the all-plugins clap API) and I'll move this over to https://github.com/surge-synthesizer/surge/issues/6137 (although I can't close the issue here)

**Comment by abique** [comment]
Best would be to try again with bitwig >= 4.3 beta 2 as the code did mature since.

**Comment by abique** [comment]
If you find other Bitwig specific issues, please can you use support@bitwig.com instead?
Thank you very much :)

**Comment by baconpaul** [comment]
I have it on my list to check surge now i've implemented note expressions I just haven't had time to have a linnstrument, bws43b2 and latest surge together yet. In theory it should work....
